### ISSUE TITLE
代码问题，请教

### ISSUE THREAD

**Issue by fd-zs** [TongkunGuan/CCD#1]
student = (
        student,
        SegHead(in_channels=config.model_seg_channel, mla_channels=128, mlahead_channels=64, num_classes=2),
        DINOHead(embed_dim, config.out_dim, use_bn=config.use_bn_in_head, norm_last_layer=config.norm_last_layer, ))
    teacher = ABIDINOModel(
        teacher,
        None,
        DINOHead(embed_dim, config.out_dim, config.use_bn_in_head), )

请问这处代码是否有问题。

**Comment by TongkunGuan** [comment]
> ```
> student = (
>     student,
>     SegHead(in_channels=config.model_seg_channel, mla_channels=128, mlahead_channels=64, num_classes=2),
>     DINOHead(embed_dim, config.out_dim, use_bn=config.use_bn_in_head, norm_last_layer=config.norm_last_layer, ))
> teacher = ABIDINOModel(
>     teacher,
>     None,
>     DINOHead(embed_dim, config.out_dim, config.use_bn_in_head), )
> ```
> 
> 请问这处代码是否有问题。

Thanks, we missed the function name.
