### ISSUE TITLE
请问mdb文件要怎样展开成数据集所需的格式？

### ISSUE THREAD

**Issue by ggxxer** [TongkunGuan/CCD#10]
感谢您的工作，初次见到mdb格式的数据集，不知道如何处理，您可以指点一二吗？

**Comment by TongkunGuan** [comment]
> 感谢您的工作，初次见到mdb格式的数据集，不知道如何处理，您可以指点一二吗？

参考 https://github.com/TongkunGuan/CCD/blob/b6a2742f5b1161a3609db809d6bc8971022c2afe/Dino/dataset/dataset.py#L133

**Comment by ggxxer** [comment]
十分感谢！
