### ISSUE TITLE
dataset.py代码问题

### ISSUE THREAD

**Issue by anzitong** [TongkunGuan/CCD#15]
198行代码中的return self._postprocessing(image, text, idx_new) text是什么？并没有被定义或赋值。

**Comment by TongkunGuan** [comment]
> 198行代码中的return self._postprocessing(image, text, idx_new) text是什么？并没有被定义或赋值。

where is the code?

**Comment by anzitong** [comment]
\CCD\Dino\dataset\dataset.py 文件中的第198行。

    def __getitem__(self, idx):
        if self.use_portion:
            idx = self.optional_ind[idx]
        datum = self.get(idx)
        if datum is None:
            return
        image, mask, idx_new = datum

        if self.mask:
            if self.is_training:
                image, mask, metric = self._process_training(image, mask)
            else:
                image, mask, metric = self._process_test(image)
            return self._postprocessing(image, mask, metric, idx_new)
        else:
            if self.is_training:
                image = self._process_training(image)
            else:
                image = self._process_test(image)
            return self._postprocessing(image, text, idx_new)

**Comment by TongkunGuan** [comment]
> \CCD\Dino\dataset\dataset.py 文件中的第198行。
> 
> ```
> def __getitem__(self, idx):
>     if self.use_portion:
>         idx = self.optional_ind[idx]
>     datum = self.get(idx)
>     if datum is None:
>         return
>     image, mask, idx_new = datum
> 
>     if self.mask:
>         if self.is_training:
>             image, mask, metric = self._process_training(image, mask)
>         else:
>             image, mask, metric = self._process_test(image)
>         return self._postprocessing(image, mask, metric, idx_new)
>     else:
>         if self.is_training:
>             image = self._process_training(image)
>         else:
>             image = self._process_test(image)
>         return self._postprocessing(image, text, idx_new)
> ```

ok! 在我的程序中我默认设置 self.mask=True 所以else部分没有被使用到

**Comment by anzitong** [comment]
非常感谢您的回复。
