### ISSUE TITLE
NameError

### ISSUE THREAD

**Issue by zhangyifei01** [TongkunGuan/CCD#2]
Dino/dataset/dataset.py
Line 16 name 'Dataset' is not defined !
Line 20 name 'PathOrStr' is not defined !
Line 40 name 'Path' is not defined !

**Comment by TongkunGuan** [comment]
> Dino/dataset/dataset.py Line 16 name 'Dataset' is not defined ! Line 20 name 'PathOrStr' is not defined ! Line 40 name 'Path' is not defined !

please check if fastai==1.0.60. If you still have questions, please contact me.

**Comment by zhangyifei01** [comment]
> > Dino/dataset/dataset.py Line 16 name 'Dataset' is not defined ! Line 20 name 'PathOrStr' is not defined ! Line 40 name 'Path' is not defined !
> 
> please check if fastai==1.0.60. If you still have questions, please contact me.

Thanks, it works !
