### ISSUE TITLE
数据集的问题

### ISSUE THREAD

**Issue by wu-yz** [TongkunGuan/CCD#3]
您好，请问数据集在哪里能下载呢？感谢！

**Comment by TongkunGuan** [comment]
> 您好，请问数据集在哪里能下载呢？感谢！

考虑到数据量比较大 上传比较麻烦 please refer to [DiG](https://github.com/ayumiymk/DiG)

注意：由于OCR-CC数据集只提供图片链接  在下载的过程中 会存在部分链接已失效 （时间越长 失效的链接越多）
所以我这边的OCR-CC数据集可能会与DiG的OCR-CC有轻微数量差异 但整体影响不大
如果你需要我这边的数据集 请通过邮箱联系我

**Comment by wu-yz** [comment]
> > 您好，请问数据集在哪里能下载呢？感谢！
> 
> 考虑到数据量比较大 上传比较麻烦 please refer to [DiG](https://github.com/ayumiymk/DiG)
> 
> 注意：由于OCR-CC数据集只提供图片链接 在下载的过程中 会存在部分链接已失效 （时间越长 失效的链接越多） 所以我这边的OCR-CC数据集可能会与DiG的OCR-CC有轻微数量差异 但整体影响不大 如果你需要我这边的数据集 请通过邮箱联系我

好嘞，可以给我一个邮箱地址吗？感谢！

**Comment by TongkunGuan** [comment]
> > > 您好，请问数据集在哪里能下载呢？感谢！
> > 
> > 
> > 考虑到数据量比较大 上传比较麻烦 please refer to [DiG](https://github.com/ayumiymk/DiG)
> > 注意：由于OCR-CC数据集只提供图片链接 在下载的过程中 会存在部分链接已失效 （时间越长 失效的链接越多） 所以我这边的OCR-CC数据集可能会与DiG的OCR-CC有轻微数量差异 但整体影响不大 如果你需要我这边的数据集 请通过邮箱联系我
> 
> 好嘞，可以给我一个邮箱地址吗？感谢！

gtk0615@sjtu.edu.cn
