### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by fd-zs** [TongkunGuan/CCD#4]
您好，请问这些包yaml opencv-python Pillow LMDB nltk six natsort scipy sklearn scikit-image matplotlib editdistance tqdm大致的版本是多少呀，直接pip会出现各种版本问题

**Comment by TongkunGuan** [comment]
> 您好，请问这些包yaml opencv-python Pillow LMDB nltk six natsort scipy sklearn scikit-image matplotlib editdistance tqdm大致的版本是多少呀，直接pip会出现各种版本问题

最近有点忙 周末或下周一回复

**Comment by TongkunGuan** [comment]
> 您好，请问这些包yaml opencv-python Pillow LMDB nltk six natsort scipy sklearn scikit-image matplotlib editdistance tqdm大致的版本是多少呀，直接pip会出现各种版本问题

已更新
