### ISSUE TITLE
Is it possible to run a single image Demo?

### ISSUE THREAD

**Issue by Shawn9257** [TongkunGuan/CCD#6]
Hi, thank for your great work! 

I have read the paper and now I am trying to test a single image OCR. Is it possible to run a single image test?

**Comment by TongkunGuan** [comment]
> Hi, thank for your great work!
> 
> I have read the paper and now I am trying to test a single image OCR. Is it possible to run a single image test?

Sorry, the script isn't provided, please modify the test.py (replaced dataloader with a single image).

**Comment by Shawn9257** [comment]
Thx for your answer.

**Comment by 0-Maxwei-0** [comment]
> Thx for your answer.

hi, have you solved this?

**Comment by bowen-upenn** [comment]
Could you please advise us on what data transformations, like transforms.Normalize, we should apply to a single user-input image? In your test.py: _get_databaunch function, we couldn't find your 'data_aug': config.dataset_data_aug in the config files provided, and what config.dataset_scheme should we use by default for a new test image? Thanks.
