### ISSUE TITLE
能否提供一个OCR_CC的百度网盘数据集链接？

### ISSUE THREAD

**Issue by FaltingsA** [TongkunGuan/CCD#9]
感谢优秀的工作！ 能否提供一个OCR_CC的百度网盘数据集链接呢？由于数据集过大，DiG的原始数据链接难以下载。

**Comment by TongkunGuan** [comment]
> 感谢优秀的工作！ 能否提供一个OCR_CC的百度网盘数据集链接呢？由于数据集过大，DiG的原始数据链接难以下载。

链接：https://pan.baidu.com/s/1PW7ef17AkwG27H_RaP0pDQ 
提取码：C2CD

**Comment by FaltingsA** [comment]
感谢啦！ great！
